In [2]:
# Imports

import pandas as pd

In [3]:
# Load Data

df = pd.read_csv(r"C:\Users\Adeeksha\OneDrive\Documents\Data Analyst\Project\E-Commerce Sales & Customer Analytics\Data\sales_raw_new_2026.csv")

df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [4]:
# removing duplicates

df = df.drop_duplicates()
df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [5]:
# fix blank columns

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        2001 2026-01-21     Neha   West   Laptop  16494  13135
1        2002 2026-01-07   Anjali  North  Monitor  35140  19722
2        2003 2026-01-28    Vikas  North   Mobile  18889  13511
3        2004 2026-01-04    Kiran  North   Mobile  89657  66187
4        2005 2026-03-02    Rahul   West   Laptop  35977  20290
..        ...        ...      ...    ...      ...    ...    ...
195      2196 2026-01-26    Kiran   East  Printer  28305  16671
196      2197 2026-01-04   Suresh  South  Printer  18669  13476
197      2198 2026-03-01   Anjali  South   Mobile  52605  33403
198      2199 2026-02-03     Neha  North   Laptop  57296  39944
199      2200 2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [6]:
# dropping na columns

df = df.dropna(subset = ['Order_Date'])
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        2001 2026-01-21     Neha   West   Laptop  16494  13135
1        2002 2026-01-07   Anjali  North  Monitor  35140  19722
2        2003 2026-01-28    Vikas  North   Mobile  18889  13511
3        2004 2026-01-04    Kiran  North   Mobile  89657  66187
4        2005 2026-03-02    Rahul   West   Laptop  35977  20290
..        ...        ...      ...    ...      ...    ...    ...
195      2196 2026-01-26    Kiran   East  Printer  28305  16671
196      2197 2026-01-04   Suresh  South  Printer  18669  13476
197      2198 2026-03-01   Anjali  South   Mobile  52605  33403
198      2199 2026-02-03     Neha  North   Laptop  57296  39944
199      2200 2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [7]:
# creating profit date and month columns 

df['Profit'] = df['Sales'] - df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,2001,2026-01-21,Neha,West,Laptop,16494,13135,3359,2026,1
1,2002,2026-01-07,Anjali,North,Monitor,35140,19722,15418,2026,1
2,2003,2026-01-28,Vikas,North,Mobile,18889,13511,5378,2026,1
3,2004,2026-01-04,Kiran,North,Mobile,89657,66187,23470,2026,1
4,2005,2026-03-02,Rahul,West,Laptop,35977,20290,15687,2026,3
...,...,...,...,...,...,...,...,...,...,...
195,2196,2026-01-26,Kiran,East,Printer,28305,16671,11634,2026,1
196,2197,2026-01-04,Suresh,South,Printer,18669,13476,5193,2026,1
197,2198,2026-03-01,Anjali,South,Mobile,52605,33403,19202,2026,3
198,2199,2026-02-03,Neha,North,Laptop,57296,39944,17352,2026,2
199,2200,2026-02-21,Priya,East,Mobile,12701,10702,1999,2026,2

## Data python +Excel + SQL

In [8]:
# imports

import pandas as pd
from sqlalchemy import create_engine

In [9]:
engine = create_engine('mysql+pymysql://root:Project0604@localhost:3309/salesdb')

In [10]:
df.to_sql(name='sales_data', con=engine, if_exists='append', index=False)

200